import React from "react";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Blocked Content Policy - couple.me",
  description:
    "Enjoy the ultimate AI girlfriend and boyfriend experience online."
};
const BlockedContentPolicy = () => {
  return (
    <div className="flex flex-col w-full bg-popover md:h-fit rounded-3xl p-3 md:p-6 mb-6">
      <h2 className="text-2xl font-bold">Blocked Content Policy</h2>

      <div className="w-full flex flex-col gap-4 mt-8">
        <p className="text-base text-muted-foreground">
          At Fab AI LTD, we are committed to providing a secure, respectful, and
          lawful online environment for all users. Although users cannot upload
          any content on our Couple.me platform (the “APP”), but can “only” chat
          and initiate the creation of AI-generated content, which is accessible
          only to the specific user in his/her private space and is not
          accessible publicly, there are categories of content strictly
          forbidden on our APP and outlined in the present Blocked Content
          Policy.
        </p>

        <p className="text-lg font-semibold mt-8">1. Prohibited Content</p>
        <p className="text-base text-muted-foreground">
          This policy applies to all content, including, but not limited to,
          text, images, videos, and any other AI-generated content created on
          our platform.
          <br />
          <br />
          a. <strong>Illegal Content:</strong> Content that contravenes local,
          national, or international laws and regulations is strictly
          prohibited. This includes, but is not limited to, content associated
          with illegal drugs, weapons, violence, or activities that advocate or
          endorse illegal actions.
          <br />
          <br />
          b. <strong>Hate Speech and Discrimination:</strong> We do not tolerate
          content that promotes hate speech, discrimination, or harassment based
          on various factors, including race, ethnicity, nationality, religion,
          gender, sexual orientation, disability, or any other protected
          characteristic.
          <br />
          <br />
          c. <strong>Violence and Harm:</strong> Content that encourages,
          glorifies, or promotes violence, self-harm, or harm to others is
          strictly prohibited. This includes content that endorses suicide,
          terrorism, or any form of harm.
          <br />
          <br />
          d. <strong>Child Exploitation:</strong> We unequivocally disallow
          content that exploits or poses a danger to minors, including but not
          limited to child pornography, sexual exploitation, or any form of harm
          or harassment towards minors.
          <br />
          <br />
          e. <strong>Content Resembling Minors:</strong> It is strictly
          prohibited trying to generate AI content resembling minors. We are
          committed to ensuring that AI-generated content on our platform does
          not bear any resemblance to minors or exploit their likeness. Any
          attempt to generate AI content resembling minors will be promptly
          reviewed and removed according to our Content Moderation procedures
          (see paragraph 3).
          <br />
          <br />
          f. <strong>Infringement on Privacy and Copyright:</strong> Any content
          that infringes upon the privacy, copyrights, trademarks, or
          intellectual property rights of individuals or entities is not
          permitted. This includes sharing personal information without consent,
          pirated content, or any unauthorized use of copyrighted material.
          <br />
          <br />
          g. <strong>Impersonation and Celebrity Content:</strong> Deceptive or
          harmful impersonation of real individuals, public figures, or
          celebrities is prohibited. This encompasses any misleading attempts to
          impersonate or misrepresent others.
        </p>

        <p className="text-lg font-semibold mt-8">2. Content Responsibility</p>
        <p className="text-base text-muted-foreground">
          You, as a user of the APP, are solely responsible for the Output
          generated by the AI Companions through text messages, voice messages,
          images, and videos. The AI Companions learn and respond based on the
          conversations you lead and the parameters you select. You understand
          and agree that Fab AI LTD does not control or endorse the content
          generated by the AI Companions. Therefore, you acknowledge that you
          are fully responsible for the Output generated by the AI and for your
          own actions while using the APP.
          <br />
          <br />
          You must ensure that your interactions with the AI Companions comply
          with applicable laws, regulations, our Terms and Policies, in
          particular the Blocked Content Policy and that you do not engage in
          any illegal, unethical, or harmful activities through the APP.
        </p>

        <p className="text-lg font-semibold mt-8">3. Content Moderation</p>
        <p className="text-base text-muted-foreground">
          While conversations between users and AI Companions are generally
          confidential, we have implemented a content moderation filter, based
          on our proprietary LLM technology to ensure compliance with our Terms
          and Policies, in particular with our Blocked Content Policy. In the
          event that the moderation filter detects any content that violates our
          terms, we reserve the right to manually review the flagged content and
          take appropriate action, which may include terminating the user&apos;s
          account. This measure is implemented to maintain a respectful and
          secure environment for all users. We strive to strike a balance
          between privacy and community standards, and we appreciate your
          understanding and cooperation in adhering to our guidelines.
        </p>

        <p className="text-lg font-semibold mt-8">
          4. Content Removal and Account Suspension
        </p>
        <p className="text-base text-muted-foreground">
          Violations of this Blocked Content Policy may result in content
          removal, account suspension, or legal action as appropriate.
        </p>

        <p className="text-lg font-semibold mt-8">5. Contact Information</p>
        <p className="text-base text-muted-foreground">
          If you have noticed any violation of these Terms from your
          perspective, content of any nature whatsoever or you have any
          questions or require further clarification regarding our Blocked
          Content Policy, please contact us at: support@couple.me or directly
          report in the APP in the “Contact” section.
        </p>

        <p className="text-lg font-semibold mt-8">6. Termination</p>
        <p className="text-base text-muted-foreground">
          We have the right to suspend or terminate the use of the APP by anyone
          engaged in the suspected infringement described above.
        </p>
      </div>
    </div>
  );
};

export default BlockedContentPolicy;
